# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               HSLee Develop
tagline:             'A Jekyll theme'
description:         'Main: iOS Developer, follow CTO Capabilities'

#
# Flags below are optional
#

timezone: Asia/Seoul

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# url:                 http://lanyon.getpoole.com
# baseurl:             ''
paginate:            5

# Custom vars
version:             1.0.0

# Use the following plug-ins
gems:
  # - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from
