# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               HSLee Develop
tagline:             'A Jekyll theme'
description:         'Main: iOS Developer, follow CTO Capabilities'

#
# Flags below are optional
#

timezone: Asia/Seoul

# About/contact
author:
  name:              HSLee
  url:               https://twitter.com/evercry
  email:             fadeguy@gmail.com

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://hsleedevelop.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

paginate:            5

# Custom vars
version:             1.0.0

# Use the following plug-ins
gems:
  # - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from
